version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y

  build:
    commands:
      - echo Build started on `date`
      - mkdir -p /var/www/html
      - cp index.html /var/www/html/
      - cp style.css /var/www/html/
      - cp script.js /var/www/html/
      - chmod +x scripts/install_nginx.sh
      - chmod +x scripts/start_nginx.sh
      - chmod +x scripts/stop_nginx.sh
      - chmod +x scripts/validate_nginx.sh

  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - '**/*'
  discard-paths: no
  name: build-output.zip
